### ISSUE TITLE
ETQ visiteur : Je peux m'enregistrer sur le site

### ISSUE THREAD

**Issue by RomainCrevecoeur** [ABC-TransitionBasCarbone/clickson-api#10]
# Contexte
Le visiteur était sur la page d'authentification mais n'avais pas de compte alors il a cliqué sur "se créer un compte"

# Tests d’acceptance
- [ ] Le visiteur professeur peut créer un compte pour son établissement
- [ ] Nom de l'établissement, Nombre élèves, Nombre personnels, Année de construction, Adresse

# Cas limites
- [ ] L'utilisateur donne une adresse email non valide -> erreur
- [ ] L'utilisateur utilise une adresse email déjà enregistré sur wordpress --> erreur

# Infos Tech
Utiliser l'api graphql pour créer un nouvel utilisateur

![Image](https://github.com/user-attachments/assets/dea49339-4db8-4291-90ef-f01a54be6f23)

**Comment by cmolle** [comment]
@RomainCrevecoeur  je me suis permis de rajouter un cas limite en cas de doublon d'adresse mail

**Comment by RomainCrevecoeur** [comment]
Vu ensemble avec @eaitezouine les mutations ne sont pas possible avec ACF
https://github.com/wp-graphql/wpgraphql-acf/issues/109

Plusieurs solutions 

1. Utiliser ce plugin peu maintenu https://github.com/zngly/wp-graphql-acf-mutations
2. Regarder si c'est le même problème avec Elementor https://fr.wordpress.org/plugins/elementor/
3.Trouver une autre solution

**Comment by RomainCrevecoeur** [comment]
Daily : 
Solution temporaire : 

- [x] Faire un table utilisateur dans Postgres (en matchant les ids) pour les pays/école

**Comment by RomainCrevecoeur** [comment]
#12

**Comment by RomainCrevecoeur** [comment]
Il faut rendre obligatoire 

- [ ] le pays
- [ ] l'école
