### ISSUE TITLE
API de gestion des sessions + facteurs d'émission

### ISSUE THREAD

**Issue by eaitezouine** [ABC-TransitionBasCarbone/clickson-api#33]
- [ ] Ajouter la table de session à la base de données
- [ ] Liste API des sessions par utilisateur
- [ ] API Ajouter une nouvelle session

![Image](https://github.com/user-attachments/assets/131743f7-ab8c-4839-afc9-c4cfcd8ef51c)

**Comment by RomainCrevecoeur** [comment]
Groupe
- [ ] Géré par le professeur
- [ ] Groupe d'élève accédant à une seule session
- [ ] Ne peux accéder qu'à un seul ou plusieurs postes d'émissions à un temps donné
- [ ] Technique : Faire le lien avec l'authentification Wordpress

Session
- [ ] Géré par le professeur
- [ ] Ajouter un lien avec l'établissement
- [ ] Données d'activité sur une année scolaire.
- [ ] Comprenant les 5 postes d'émissions.
- [ ] Il est possible de dupliquer les sessions
- [ ] Une session peut avoir plusieurs groupes

Postes d'émissions
- [ ] Accès par un seul groupe en même temps

**Comment by RomainCrevecoeur** [comment]
Lié à https://github.com/ABC-TransitionBasCarbone/clickson-api/issues/8

**Comment by RomainCrevecoeur** [comment]
ajoute la ligne dans le Wordpress
`define( 'JWT_AUTH_SECRET_KEY',         'Cy$^z>,;sLa)N}fb+-(^WdwD0%iP2]z@-4wn=;Ny?LHLAuufW3GtsB&?!X+HL:ho' );
`à wp-config.php
